title: CMS

tabs:
  content:
    label: Content
    sections:
      introductionSection:
        type: fields
        fields:
          introHeadline:
            label: Page Introduction
            type: headline
            text: Introduction Section
          intro:
            label: Introduction
            type: textarea
            help: Enter the introduction text for the page.
            buttons:
              - bold
              - italic
              - link
              - email
              - "|"
              - ul
              - ol
          quickInfo:
            label: Quick info
            type: textarea
            help: Leave this blank to hide it.
            buttons:
              - bold
              - italic
              - link
              - email
              - "|"
              - ul
              - ol
            
      pageSections:
        type: fields
        fields:
          sectionsHeadline:
            label: Content Sections
            type: headline
            text: Page Sections
          sections:
            label: Page Sections
            type: structure
            fields:
              sectionTitle:
                label: Section Title
                type: text
              sectionBody:
                label: Section Body
                type: textarea
                buttons:
                  - bold
                  - italic
                  - link
                  - email
                  - "|"
                  - ul
                  - ol
              subSections:
                label: Subsections
                type: structure
                fields:
                  subSectionTitle:
                    label: Subsection Title
                    type: text
                  subSectionIcon:
                    label: Subsection Icon
                    type: files
                    max: 1
                    template: image
                    width: 1/2
                  subSectionColor:
                    label: Subsection Color
                    type: color
                    default: "#e4e4e4"
                    help: Choose a subsection color.
                    width: 1/2
                  subSectionBody:
                    label: Subsection Body
                    type: textarea
                    buttons:
                      - bold
                      - italic
                      - link
                      - email
                      - "|"
                      - ul
                      - ol
                
      teamSection:
        type: fields
        fields:
          teamHeadline:
            label: Clinical Team
            type: headline
            text: Team Members Section
          team:
            label: Team Members
            type: structure
            fields:
              name:
                label: Name
                type: text
              about:
                label: About
                type: textarea
                buttons:
                  - bold
                  - italic
                  - link
                  - email
                  - "|"
                  - ul
                  - ol
              teamMemberImage:
                label: Team Member Image
                type: files
                max: 1
                template: image
              professionalLogos:
                label: Professional Logos
                type: files
                help: Upload professional logos associated with this team member.
                template: image
              pageActive:
                label: Page active?
                type: toggle
                text: 
                
      contactSection:
        type: fields
        fields:
          contactHeadline:
            label: Contact Information
            type: headline
            text: Contact Information
          contactPhone:
            label: Phone
            type: tel
            width: 1/2
          contactEmail:
            label: Email
            type: email
            width: 1/2

      annocuementSection:
        type: fields
        fields:

          # Add the announcement banner fields here
          announcementBannerHeadline:
            label: Announcement Banner
            type: headline
            text: Announcement Banner Settings
          announcementBanner:
            label: Announcement Banner Text
            type: textarea
            help: Enter the text for the announcement banner.
            width: 1/2
            buttons:
              - bold
              - italic
              - link
              - email
              - "|"
              - ul
              - ol
          showBanner:
            label: Display Announcement Banner?
            type: toggle
            help: Toggle on to display the announcement banner on the website.
            width: 1/2
  
      appearanceSection:
        type: fields
        fields:
          appearanceHeadline:
            label: Appearance Settings
            type: headline
            text: Appearance Customization
          textColor:
            label: Text Color
            type: color
            default: "#000000"
            help: Choose a custom text color.
            width: 1/4
          backgroundColor:
            label: Background Color
            type: color
            default: "#ffffff"
            help: Choose a custom background color.
            width: 1/4

      headerImageSection:
        type: fields
        fields:
          imageHeadline:
            label: Logo & window images
            type: headline
            text: Header Image Section
          headerImage:
            label: Header Image
            type: files
            max: 1
            help: Upload a header image for the page.
            template: image
            width: 1/4
          windowActive:
            label: Window active?
            type: toggle
            text: 
            width: 1/4

  filesTab:
    label: Files
    sections:
      allFilesSection:
        type: files
        fields:
          filesHeadline:
            label: All Uploaded Files
            type: headline
            text: Files Section
        headline: All Files
        layout: cards
        info: "{{ file.dimensions }}"
        text: "{{ file.filename }}"
        size: "tiny"
        image:
          back: "black"
          cover: true
